services:
    tune_backend:
        build:
            context: .
            dockerfile: services/backend/Dockerfile
        image: tune_backend
        container_name: tune_backend
        networks:
            - tune_internal
            - tune_internet
        volumes:
            - ${DEV_SAMPLE_STORAGE}:/tmp/samples
            - ./services/backend/src/:/app
    tune_frontend:
        build:
            context: .
            dockerfile: services/frontend/Dockerfile
        image: tune_frontend
        container_name: tune_frontend
        networks:
            - tune_internal

    tune_gui:
        build:
            context: .
            dockerfile: services/gui/Dockerfile
        image: tune_gui
        container_name: tune_gui
        privileged: true
        networks:
            - tune_internal
        environment:
            - DISPLAY=:0
            - PULSE_SERVER=unix:/tmp/pulse/native
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./services/gui/start.sh:/home/chromium/start.sh
            - /var/run/user/1004/pulse/native:/tmp/pulse/native
            #- /home/tunecube/.config/pulse/cookie:/home/chromium/.config/pulse/cookie 
networks:
    tune_internal:
        internal: true  

    tune_internet:
        driver: bridge
