services:
    tune_backend:
        build:
            context: .
            dockerfile: services/backend/Dockerfile
        image: tune_backend
        container_name: tune_backend
        networks:
            tune_internal:
            tune_internet:
        volumes:
            - ${DEV_SAMPLE_STORAGE}:/tmp/samples
        profiles:
            - default

    tune_backend_develop:
        image: tune_backend
        container_name: tune_backend_develop
        networks:
            tune_internal:
                aliases:
                    - tune_backend
            tune_internet:
        volumes:
            - ${DEV_SAMPLE_STORAGE}:/tmp/samples
            - ./services/backend/src/:/app
        profiles:
            - develop

    tune_frontend:
        build:
            context: .
            dockerfile: services/frontend/Dockerfile
        image: tune_frontend
        container_name: tune_frontend
        networks:
            tune_internal:
        profiles:
            - default

    tune_frontend_develop:
        image: tune_frontend
        container_name: tune_frontend_develop
        networks:
            tune_internal:
                aliases:
                    - tune_frontend
        volumes:
            - ./services/frontend/src/:/app
        profiles:
            - develop
    tune_gui:
        build:
            context: .
            dockerfile: services/gui/Dockerfile
        image: tune_gui
        container_name: tune_gui
        privileged: true
        networks:
            tune_internal:
        environment:
            - DISPLAY=:0
            - PULSE_SERVER=unix:/tmp/pulse/native
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /var/run/user/1004/pulse/native:/tmp/pulse/native
        profiles:
            - default

    tune_gui_develop:
        image: tune_gui
        container_name: tune_gui_develop
        privileged: true
        networks:
            tune_internal:
        environment:
            - DISPLAY=:0
            - PULSE_SERVER=unix:/tmp/pulse/native
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /var/run/user/1004/pulse/native:/tmp/pulse/native
            - ./services/gui/start.sh:/home/chromium/start.sh
        profiles:
            - develop
networks:
    tune_internal:
        internal: true  

    tune_internet:
        driver: bridge
